export const GET_AUTHORS = 'GET_AUTHORS';
export const SET_AUTHORS = 'SET_AUTHORS';
export const CLEAR_AUTHORS = 'CLEAR_AUTHORS';
export const ADD_NEW_AUTHOR = 'ADD_NEW_AUTHOR';
export const SET_NEW_AUTHOR = 'SET_NEW_AUTHOR';
export const SET_USER_SAVED_PROFILE = 'SET_USER_SAVED_PROFILE';
